title: 'Badstu'
baseURL: 'https://badstu.github.io/'

defaultContentLanguage: zh
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

build:
  writeStats: true
enableGitInfo: false
summaryLength: 80
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
disableAliases: true

outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture

timeout: 600000

taxonomies:
  author: authors
  category: categories
  tag: tags
  publication_type: publication_types

markup:
  _merge: deep
  highlight:
    lineNos: false

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^CI$
  exec:
    allow:
      - ^(dart-)?sass$
      - ^go$
      - ^git$
      - ^node$
      - ^npx$
      - ^postcss$
      - ^tailwindcss$
  node:
    permissions:
      allowAddons:
        - tailwindcss
      allowChildProcess:
        - tailwindcss
      allowRead:
        - .
      allowWorker:
        - tailwindcss
      allowWrite: []
      disable: false
sitemap:
  _merge: deep
