zh:
  locale: zh-Hans
  contentDir: content/zh
  title: Sean
  weight: 1
  params:
    description: Sean 的个人主页与生活博客
  menus:
    main:
      - name: 首页
        url: /
        weight: 10
      - name: 博客
        url: /blog/
        weight: 20

en:
  locale: en-US
  contentDir: content/en
  title: Sean
  weight: 2
  params:
    description: Sean's personal homepage and life blog
  menus:
    main:
      - name: Home
        url: /
        weight: 10
      - name: Blog
        url: /blog/
        weight: 20
