media:
  - name: blog_images
    label: 博客图片
    input: static/uploads/blog
    output: /uploads/blog
    rename: safe
    categories: [image]

content:
  - name: blog
    label: 博客文章
    type: collection
    path: content/zh/blog
    exclude: ['_index.md']
    filename: '{primary}.md'
    view:
      fields: [title, date, categories, draft]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: 标题
        type: string
        required: true
      - name: date
        label: 发布时间
        type: date
        required: true
      - name: summary
        label: 摘要
        type: text
        required: true
      - name: cover
        label: 封面图片
        type: image
        options:
          media: blog_images
      - name: categories
        label: 分类
        type: string
        list: true
      - name: tags
        label: 标签
        type: string
        list: true
      - name: featured
        label: 首页推荐
        type: boolean
        default: false
      - name: draft
        label: 草稿
        type: boolean
        default: true
      - name: body
        label: 正文
        type: rich-text
        options:
          media: blog_images
          path: static/uploads/blog
          rename: true
